export interface ComponentCategory {
  slug: string;
  name: string;
  components: { name: string }[];
  isNew?: boolean;
}

export const categories: ComponentCategory[] = [
  {
    slug: "accordion",
    name: "Accordion",
    components: [
      { name: "comp-334" },
      { name: "comp-335" },
      { name: "comp-336" },
      { name: "comp-337" },
      { name: "comp-338" },
      { name: "comp-339" },
      { name: "comp-340" },
      { name: "comp-341" },
      { name: "comp-342" },
      { name: "comp-343" },
      { name: "comp-344" },
      { name: "comp-345" },
      { name: "comp-346" },
      { name: "comp-347" },
      { name: "comp-348" },
      { name: "comp-349" },
      { name: "comp-350" },
      { name: "comp-351" },
      { name: "comp-352" },
      { name: "comp-353" },
    ],
  },
  {
    slug: "alert",
    name: "Alert",
    components: [
      { name: "comp-267" },
      { name: "comp-268" },
      { name: "comp-269" },
      { name: "comp-270" },
      { name: "comp-271" },
      { name: "comp-272" },
      { name: "comp-273" },
      { name: "comp-274" },
      { name: "comp-275" },
      { name: "comp-276" },
      { name: "comp-277" },
      { name: "comp-278" },
    ],
  },
  {
    slug: "avatar",
    name: "Avatar",
    components: [
      { name: "comp-390" },
      { name: "comp-391" },
      { name: "comp-392" },
      { name: "comp-393" },
      { name: "comp-394" },
      { name: "comp-395" },
      { name: "comp-396" },
      { name: "comp-397" },
      { name: "comp-398" },
      { name: "comp-399" },
      { name: "comp-400" },
      { name: "comp-401" },
      { name: "comp-402" },
      { name: "comp-403" },
      { name: "comp-404" },
      { name: "comp-405" },
      { name: "comp-406" },
      { name: "comp-407" },
      { name: "comp-408" },
      { name: "comp-409" },
      { name: "comp-410" },
      { name: "comp-411" },
      { name: "comp-412" },
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    components: [
      { name: "comp-413" },
      { name: "comp-414" },
      { name: "comp-415" },
      { name: "comp-416" },
      { name: "comp-417" },
      { name: "comp-418" },
      { name: "comp-419" },
      { name: "comp-420" },
      { name: "comp-421" },
      { name: "comp-422" },
      { name: "comp-423" },
      { name: "comp-424" },
      { name: "comp-425" },
    ],
  },
  {
    slug: "banner",
    name: "Banner",
    components: [
      { name: "comp-301" },
      { name: "comp-302" },
      { name: "comp-303" },
      { name: "comp-304" },
      { name: "comp-305" },
      { name: "comp-306" },
      { name: "comp-307" },
      { name: "comp-308" },
      { name: "comp-309" },
      { name: "comp-310" },
      { name: "comp-311" },
      { name: "comp-312" },
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    components: [
      { name: "comp-446" },
      { name: "comp-447" },
      { name: "comp-448" },
      { name: "comp-449" },
      { name: "comp-450" },
      { name: "comp-451" },
      { name: "comp-452" },
      { name: "comp-453" },
    ],
  },
  {
    slug: "button",
    name: "Button",
    components: [
      { name: "comp-78" },
      { name: "comp-79" },
      { name: "comp-80" },
      { name: "comp-81" },
      { name: "comp-82" },
      { name: "comp-83" },
      { name: "comp-84" },
      { name: "comp-85" },
      { name: "comp-86" },
      { name: "comp-87" },
      { name: "comp-88" },
      { name: "comp-89" },
      { name: "comp-90" },
      { name: "comp-91" },
      { name: "comp-92" },
      { name: "comp-93" },
      { name: "comp-94" },
      { name: "comp-95" },
      { name: "comp-96" },
      { name: "comp-97" },
      { name: "comp-98" },
      { name: "comp-99" },
      { name: "comp-100" },
      { name: "comp-101" },
      { name: "comp-129" },
      { name: "comp-130" },
      { name: "comp-102" },
      { name: "comp-103" },
      { name: "comp-104" },
      { name: "comp-105" },
      { name: "comp-106" },
      { name: "comp-107" },
      { name: "comp-108" },
      { name: "comp-109" },
      { name: "comp-110" },
      { name: "comp-111" },
      { name: "comp-112" },
      { name: "comp-113" },
      { name: "comp-114" },
      { name: "comp-131" },
      { name: "comp-115" },
      { name: "comp-116" },
      { name: "comp-117" },
      { name: "comp-118" },
      { name: "comp-119" },
      { name: "comp-120" },
      { name: "comp-121" },
      { name: "comp-122" },
      { name: "comp-123" },
      { name: "comp-124" },
      { name: "comp-125" },
      { name: "comp-126" },
      { name: "comp-127" },
      { name: "comp-128" },
    ],
  },
  {
    slug: "calendar-date-picker",
    name: "Calendar & Date picker",
    components: [
      { name: "comp-487" },
      { name: "comp-488" },
      { name: "comp-489" },
      { name: "comp-490" },
      { name: "comp-491" },
      { name: "comp-492" },
      { name: "comp-493" },
      { name: "comp-494" },
      { name: "comp-495" },
      { name: "comp-496" },
      { name: "comp-497" },
      { name: "comp-498" },
      { name: "comp-499" },
      { name: "comp-500" },
      { name: "comp-501" },
      { name: "comp-502" },
      { name: "comp-503" },
      { name: "comp-504" },
      { name: "comp-505" },
      { name: "comp-506" },
      { name: "comp-507" },
      { name: "comp-508" },
      { name: "comp-509" },
      { name: "comp-510" },
      { name: "comp-41" },
      { name: "comp-42" },
      { name: "comp-511" },
      { name: "comp-512" },
    ],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    components: [
      { name: "comp-132" },
      { name: "comp-133" },
      { name: "comp-134" },
      { name: "comp-135" },
      { name: "comp-136" },
      { name: "comp-137" },
      { name: "comp-138" },
      { name: "comp-139" },
      { name: "comp-151" },
      { name: "comp-140" },
      { name: "comp-141" },
      { name: "comp-142" },
      { name: "comp-143" },
      { name: "comp-144" },
      { name: "comp-145" },
      { name: "comp-146" },
      { name: "comp-147" },
      { name: "comp-148" },
      { name: "comp-149" },
      { name: "comp-150" },
    ],
  },
  {
    slug: "dialog",
    name: "Dialog",
    components: [
      { name: "comp-313" },
      { name: "comp-314" },
      { name: "comp-315" },
      { name: "comp-316" },
      { name: "comp-317" },
      { name: "comp-318" },
      { name: "comp-319" },
      { name: "comp-320" },
      { name: "comp-321" },
      { name: "comp-322" },
      { name: "comp-323" },
      { name: "comp-324" },
      { name: "comp-325" },
      { name: "comp-326" },
      { name: "comp-327" },
      { name: "comp-328" },
      { name: "comp-329" },
      { name: "comp-330" },
      { name: "comp-331" },
      { name: "comp-332" },
      { name: "comp-333" },
    ],
  },
  {
    slug: "dropdown",
    name: "Dropdown",
    components: [
      { name: "comp-366" },
      { name: "comp-367" },
      { name: "comp-368" },
      { name: "comp-369" },
      { name: "comp-370" },
      { name: "comp-371" },
      { name: "comp-372" },
      { name: "comp-373" },
      { name: "comp-374" },
      { name: "comp-375" },
      { name: "comp-376" },
      { name: "comp-377" },
      { name: "comp-378" },
      { name: "comp-379" },
      { name: "comp-380" },
    ],
  },
  {
    slug: "input",
    name: "Input",
    components: [
      { name: "comp-01" },
      { name: "comp-02" },
      { name: "comp-03" },
      { name: "comp-04" },
      { name: "comp-05" },
      { name: "comp-06" },
      { name: "comp-07" },
      { name: "comp-08" },
      { name: "comp-09" },
      { name: "comp-10" },
      { name: "comp-11" },
      { name: "comp-12" },
      { name: "comp-13" },
      { name: "comp-14" },
      { name: "comp-15" },
      { name: "comp-16" },
      { name: "comp-17" },
      { name: "comp-18" },
      { name: "comp-19" },
      { name: "comp-20" },
      { name: "comp-21" },
      { name: "comp-22" },
      { name: "comp-23" },
      { name: "comp-24" },
      { name: "comp-25" },
      { name: "comp-26" },
      { name: "comp-27" },
      { name: "comp-28" },
      { name: "comp-29" },
      { name: "comp-30" },
      { name: "comp-31" },
      { name: "comp-32" },
      { name: "comp-33" },
      { name: "comp-34" },
      { name: "comp-35" },
      { name: "comp-36" },
      { name: "comp-37" },
      { name: "comp-38" },
      { name: "comp-39" },
      { name: "comp-40" },
      { name: "comp-41" },
      { name: "comp-42" },
      { name: "comp-43" },
      { name: "comp-44" },
      { name: "comp-45" },
      { name: "comp-58" },
      { name: "comp-46" },
      { name: "comp-47" },
      { name: "comp-48" },
      { name: "comp-49" },
      { name: "comp-50" },
      { name: "comp-51" },
      { name: "comp-52" },
      { name: "comp-53" },
      { name: "comp-54" },
      { name: "comp-55" },
      { name: "comp-486" },
      { name: "comp-56" },
      { name: "comp-57" },
    ],
  },
  {
    slug: "notification",
    name: "Notification",
    components: [
      { name: "comp-279" },
      { name: "comp-280" },
      { name: "comp-281" },
      { name: "comp-282" },
      { name: "comp-283" },
      { name: "comp-284" },
      { name: "comp-285" },
      { name: "comp-286" },
      { name: "comp-287" },
      { name: "comp-288" },
      { name: "comp-289" },
      { name: "comp-290" },
      { name: "comp-291" },
      { name: "comp-292" },
      { name: "comp-293" },
      { name: "comp-294" },
      { name: "comp-295" },
      { name: "comp-296" },
      { name: "comp-297" },
      { name: "comp-298" },
      { name: "comp-299" },
      { name: "comp-300" },
    ],
  },
  {
    slug: "pagination",
    name: "Pagination",
    components: [
      { name: "comp-454" },
      { name: "comp-455" },
      { name: "comp-456" },
      { name: "comp-457" },
      { name: "comp-458" },
      { name: "comp-459" },
      { name: "comp-460" },
      { name: "comp-461" },
      { name: "comp-462" },
      { name: "comp-463" },
      { name: "comp-464" },
      { name: "comp-465" },
    ],
  },
  {
    slug: "popover",
    name: "Popover",
    components: [
      { name: "comp-381" },
      { name: "comp-382" },
      { name: "comp-383" },
      { name: "comp-384" },
      { name: "comp-385" },
      { name: "comp-386" },
      { name: "comp-387" },
      { name: "comp-388" },
      { name: "comp-389" },
    ],
  },
  {
    slug: "radio",
    name: "Radio",
    components: [
      { name: "comp-152" },
      { name: "comp-153" },
      { name: "comp-154" },
      { name: "comp-155" },
      { name: "comp-156" },
      { name: "comp-157" },
      { name: "comp-158" },
      { name: "comp-159" },
      { name: "comp-160" },
      { name: "comp-161" },
      { name: "comp-162" },
      { name: "comp-163" },
      { name: "comp-164" },
      { name: "comp-165" },
      { name: "comp-166" },
      { name: "comp-171" },
      { name: "comp-167" },
      { name: "comp-168" },
      { name: "comp-169" },
      { name: "comp-170" },
    ],
  },
  {
    slug: "select",
    name: "Select",
    components: [
      { name: "comp-189" },
      { name: "comp-190" },
      { name: "comp-191" },
      { name: "comp-192" },
      { name: "comp-193" },
      { name: "comp-194" },
      { name: "comp-195" },
      { name: "comp-196" },
      { name: "comp-197" },
      { name: "comp-198" },
      { name: "comp-199" },
      { name: "comp-200" },
      { name: "comp-201" },
      { name: "comp-202" },
      { name: "comp-203" },
      { name: "comp-204" },
      { name: "comp-205" },
      { name: "comp-206" },
      { name: "comp-207" },
      { name: "comp-208" },
      { name: "comp-209" },
      { name: "comp-210" },
      { name: "comp-211" },
      { name: "comp-212" },
      { name: "comp-213" },
      { name: "comp-214" },
      { name: "comp-215" },
      { name: "comp-216" },
      { name: "comp-217" },
      { name: "comp-218" },
      { name: "comp-219" },
      { name: "comp-220" },
      { name: "comp-221" },
      { name: "comp-222" },
      { name: "comp-223" },
      { name: "comp-224" },
      { name: "comp-225" },
      { name: "comp-226" },
      { name: "comp-227" },
      { name: "comp-228" },
      { name: "comp-229" },
      { name: "comp-230" },
      { name: "comp-231" },
      { name: "comp-232" },
      { name: "comp-233" },
      { name: "comp-234" },
      { name: "comp-235" },
      { name: "comp-236" },
      { name: "comp-237" },
      { name: "comp-238" },
      { name: "comp-239" },
    ],
  },
  {
    slug: "slider",
    name: "Slider",
    components: [
      { name: "comp-240" },
      { name: "comp-241" },
      { name: "comp-242" },
      { name: "comp-243" },
      { name: "comp-244" },
      { name: "comp-245" },
      { name: "comp-246" },
      { name: "comp-247" },
      { name: "comp-248" },
      { name: "comp-249" },
      { name: "comp-250" },
      { name: "comp-251" },
      { name: "comp-252" },
      { name: "comp-253" },
      { name: "comp-254" },
      { name: "comp-255" },
      { name: "comp-256" },
      { name: "comp-257" },
      { name: "comp-258" },
      { name: "comp-259" },
      { name: "comp-260" },
      { name: "comp-261" },
      { name: "comp-262" },
      { name: "comp-263" },
      { name: "comp-264" },
      { name: "comp-265" },
      { name: "comp-266" },
    ],
  },
  {
    slug: "stepper",
    name: "Stepper",
    components: [
      { name: "comp-513" },
      { name: "comp-514" },
      { name: "comp-515" },
      { name: "comp-516" },
      { name: "comp-517" },
      { name: "comp-518" },
      { name: "comp-519" },
      { name: "comp-520" },
      { name: "comp-521" },
      { name: "comp-522" },
      { name: "comp-523" },
      { name: "comp-524" },
      { name: "comp-525" },
      { name: "comp-526" },
      { name: "comp-527" },
      { name: "comp-528" },
      { name: "comp-529" },
    ],
  },
  {
    slug: "switch",
    name: "Switch",
    components: [
      { name: "comp-172" },
      { name: "comp-173" },
      { name: "comp-174" },
      { name: "comp-175" },
      { name: "comp-176" },
      { name: "comp-177" },
      { name: "comp-178" },
      { name: "comp-179" },
      { name: "comp-180" },
      { name: "comp-181" },
      { name: "comp-182" },
      { name: "comp-183" },
      { name: "comp-184" },
      { name: "comp-185" },
      { name: "comp-186" },
      { name: "comp-187" },
      { name: "comp-188" },
    ],
  },
  {
    slug: "table",
    name: "Table",
    components: [
      { name: "comp-466" },
      { name: "comp-467" },
      { name: "comp-468" },
      { name: "comp-469" },
      { name: "comp-470" },
      { name: "comp-471" },
      { name: "comp-472" },
      { name: "comp-473" },
      { name: "comp-474" },
      { name: "comp-475" },
      { name: "comp-476" },
      { name: "comp-477" },
      { name: "comp-478" },
      { name: "comp-479" },
      { name: "comp-480" },
      { name: "comp-481" },
      { name: "comp-482" },
      { name: "comp-483" },
      { name: "comp-484" },
      { name: "comp-485" },
    ],
  },
  {
    slug: "tabs",
    name: "Tabs",
    components: [
      { name: "comp-426" },
      { name: "comp-427" },
      { name: "comp-428" },
      { name: "comp-429" },
      { name: "comp-430" },
      { name: "comp-431" },
      { name: "comp-432" },
      { name: "comp-433" },
      { name: "comp-434" },
      { name: "comp-435" },
      { name: "comp-436" },
      { name: "comp-437" },
      { name: "comp-438" },
      { name: "comp-439" },
      { name: "comp-440" },
      { name: "comp-441" },
      { name: "comp-442" },
      { name: "comp-443" },
      { name: "comp-444" },
      { name: "comp-445" },
    ],
  },
  {
    slug: "textarea",
    name: "Textarea",
    components: [
      { name: "comp-59" },
      { name: "comp-60" },
      { name: "comp-61" },
      { name: "comp-62" },
      { name: "comp-63" },
      { name: "comp-64" },
      { name: "comp-65" },
      { name: "comp-66" },
      { name: "comp-67" },
      { name: "comp-68" },
      { name: "comp-69" },
      { name: "comp-70" },
      { name: "comp-71" },
      { name: "comp-72" },
      { name: "comp-73" },
      { name: "comp-74" },
      { name: "comp-75" },
      { name: "comp-76" },
      { name: "comp-77" },
    ],
  },
  {
    slug: "timeline",
    name: "Timeline",
    isNew: true,
    components: [
      { name: "comp-530" },
      { name: "comp-531" },
      { name: "comp-532" },
      { name: "comp-533" },
      { name: "comp-534" },
      { name: "comp-535" },
      { name: "comp-536" },
      { name: "comp-537" },
      { name: "comp-538" },
      { name: "comp-539" },
      { name: "comp-540" },
      { name: "comp-541" },
    ],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    components: [
      { name: "comp-354" },
      { name: "comp-355" },
      { name: "comp-356" },
      { name: "comp-357" },
      { name: "comp-358" },
      { name: "comp-359" },
      { name: "comp-360" },
      { name: "comp-361" },
      { name: "comp-362" },
      { name: "comp-363" },
      { name: "comp-364" },
      { name: "comp-365" },
    ],
  },
];

export function getCategory(slug: string): ComponentCategory | undefined {
  return categories.find((category) => category.slug === slug);
}
