import type { Schema } from "./registry-schema";

export type ComponentDefinition = Partial<
  Pick<Schema, "dependencies" | "devDependencies" | "registryDependencies" | "cssVars" | "tailwind">
> & {
  name: string;
  path: string;
};

export const components: ComponentDefinition[] = [
  {
    name: "card-number",
    path: "../components/inputs/card-number.tsx",
    registryDependencies: ["input", "label"],
    dependencies: ["react-payment-inputs"],
  },
  {
    name: "copy-to-clipboard",
    path: "../components/inputs/copy-to-clipboard.tsx",
    registryDependencies: ["input", "label", "tooltip"],
    dependencies: [],
  },
  {
    name: "cvv-code-input",
    path: "../components/inputs/cvv-code-input.tsx",
    registryDependencies: ["input", "label"],
    dependencies: ["react-payment-inputs"],
  },
  {
    name: "date-and-time-input",
    path: "../components/inputs/date-and-time-input.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "date-input",
    path: "../components/inputs/date-input.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "date-picker",
    path: "../components/inputs/date-picker.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "date-range-picker-unavailable",
    path: "../components/inputs/date-range-picker-unavailable.tsx",
    registryDependencies: [],
    dependencies: ["react-aria", "react-aria-components"],
  },
  {
    name: "date-range-picker",
    path: "../components/inputs/date-range-picker.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "expiry-date",
    path: "../components/inputs/expiry-date.tsx",
    registryDependencies: ["input", "label"],
    dependencies: ["react-payment-inputs"],
  },
  {
    name: "file-input",
    path: "../components/inputs/file-input.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-card-detail",
    path: "../components/inputs/input-card-detail.tsx",
    registryDependencies: ["input"],
    dependencies: ["react-payment-inputs"],
  },
  {
    name: "input-disabled",
    path: "../components/inputs/input-disabled.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-required",
    path: "../components/inputs/input-required.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-simple",
    path: "../components/inputs/input-simple.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-button",
    path: "../components/inputs/input-with-button.tsx",
    registryDependencies: ["button", "input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-character-limit",
    path: "../components/inputs/input-with-character-limit.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-characters-left",
    path: "../components/inputs/input-with-characters-left.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-clear-button",
    path: "../components/inputs/input-with-clear-button.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-addon",
    path: "../components/inputs/input-with-end-addon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-button",
    path: "../components/inputs/input-with-end-button.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-icon-button",
    path: "../components/inputs/input-with-end-icon-button.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-icon",
    path: "../components/inputs/input-with-end-icon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-inline-addon",
    path: "../components/inputs/input-with-end-inline-addon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-inline-button",
    path: "../components/inputs/input-with-end-inline-button.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-end-select",
    path: "../components/inputs/input-with-end-select.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-error",
    path: "../components/inputs/input-with-error.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-gray-background",
    path: "../components/inputs/input-with-gray-background.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-helper-text",
    path: "../components/inputs/input-with-helper-text.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-hint",
    path: "../components/inputs/input-with-hint.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-inline-addons",
    path: "../components/inputs/input-with-inline-addons.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-inline-start-and-end-add-on",
    path: "../components/inputs/input-with-inline-start-and-end-add-on.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-inner-tags",
    path: "../components/inputs/input-with-inner-tags.tsx",
    registryDependencies: ["label"],
    dependencies: ["emblor"],
  },
  {
    name: "input-with-inset-label",
    path: "../components/inputs/input-with-inset-label.tsx",
    registryDependencies: [],
    dependencies: [],
  },
  {
    name: "input-with-label-animation",
    path: "../components/inputs/input-with-label-animation.tsx",
    registryDependencies: ["input"],
    dependencies: [],
  },
  {
    name: "input-with-mask",
    path: "../components/inputs/input-with-mask.tsx",
    registryDependencies: ["input", "label"],
    dependencies: ["use-mask-input"],
  },
  {
    name: "input-with-overlapping-label",
    path: "../components/inputs/input-with-overlapping-label.tsx",
    registryDependencies: ["input"],
    dependencies: [],
  },
  {
    name: "input-with-password-strength-indicator",
    path: "../components/inputs/input-with-password-strength-indicator.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-ring",
    path: "../components/inputs/input-with-ring.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-start-addon",
    path: "../components/inputs/input-with-start-addon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-start-icon",
    path: "../components/inputs/input-with-start-icon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-start-inline-addon",
    path: "../components/inputs/input-with-start-inline-addon.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-start-select",
    path: "../components/inputs/input-with-start-select.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "input-with-tags",
    path: "../components/inputs/input-with-tags.tsx",
    registryDependencies: ["label"],
    dependencies: ["emblor"],
  },
  {
    name: "number-input-with-chevrons",
    path: "../components/inputs/number-input-with-chevrons.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "number-input-with-plus-minus-buttons",
    path: "../components/inputs/number-input-with-plus-minus-buttons.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "otp-input-double",
    path: "../components/inputs/otp-input-double.tsx",
    registryDependencies: ["label"],
    dependencies: ["input-otp"],
  },
  {
    name: "otp-input-single",
    path: "../components/inputs/otp-input-single.tsx",
    registryDependencies: ["label"],
    dependencies: ["input-otp"],
  },
  {
    name: "otp-input-spaced",
    path: "../components/inputs/otp-input-spaced.tsx",
    registryDependencies: ["label"],
    dependencies: ["input-otp"],
  },
  {
    name: "phone-number-input",
    path: "../components/inputs/phone-number-input.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "read-only-input",
    path: "../components/inputs/read-only-input.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "search-input-with-icon-and-button",
    path: "../components/inputs/search-input-with-icon-and-button.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "search-input-with-kbd",
    path: "../components/inputs/search-input-with-kbd.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "search-input-with-loader",
    path: "../components/inputs/search-input-with-loader.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "show-hide-password-input",
    path: "../components/inputs/show-hide-password-input.tsx",
    registryDependencies: ["input", "label"],
    dependencies: [],
  },
  {
    name: "time-input-with-end-icon",
    path: "../components/inputs/time-input-with-end-icon.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "time-input-with-start-icon",
    path: "../components/inputs/time-input-with-start-icon.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "time-input",
    path: "../components/inputs/time-input.tsx",
    registryDependencies: [],
    dependencies: ["react-aria-components"],
  },
  {
    name: "timestamp",
    path: "../components/inputs/timestamp.tsx",
    registryDependencies: ["input", "label"],
    dependencies: ["use-mask-input"],
  },
];
